#ifndef _INDIA_H
#define _INDIA_H


#define BATSMAN1	SRIKAR_DAWAN
#define BATSMAN2	ROHIT_SHARMA
#define BATSMAN3	VIRAT_KOHLI
#define BATSMAN4	KL_RAHUL
#define BATSMAN5	MS_DHONI
#define BATSMAN6	HARDIK_PANDYA
#define BATSMAN7	RAVINDER_JADAJA
#define BATSMAN8	SANJU_SAMSON
#define BATSMAN9	BUMRAH
#define BATSMAN10	MOHAMMAD_SHAMI
#define BATSMAN11	CHAGAR

#endif
