#ifndef _WESTINDIES_H
#define _WESTINDIES_H

#define WESTINDIESTOPLIST	{"DARREN_BRAVO","CHRIS_GAYLE","EVIN_LEWIS","SHIMRON_HETMYER",\
			 "ANDREW_RUSSELL","SHAI_HOPE","JASON_HOLDER","CARLOS_BARATHWAITE",\
			 "KEMAR_ROACH","ASHLEY_NURSE","OSHANE_THOMAS"}

#if 0
#define BATSMAN1	"DARREN_BRAVO"
#define BATSMAN2	"CHRIS_GAYLE"
#define BATSMAN3	"EVIN_LEWIS"
#define BATSMAN4	"SHIMRON_HETMYER"
#define BATSMAN5	"ANDREW_RUSSELL"
#define BATSMAN6	"SHAI_HOPE"
#define BATSMAN7	"JASON_HOLDER"
#define BATSMAN8	"CARLOS_BARATHWAITE"
#define BATSMAN9	"KEMAR_ROACH"
#define BATSMAN10	"ASHLEY_NURSE"
#define BATSMAN11	"OSHANE_THOMAS"


#define BATSMAN1	1
#define BATSMAN2	2
#define BATSMAN3	3
#define BATSMAN4	4
#define BATSMAN5	5
#define BATSMAN6	6
#define BATSMAN7	7
#define BATSMAN8	8
#define BATSMAN9	9
#define BATSMAN10	10
#define BATSMAN11	11

#define WESTINDIES \
	{ BATSMAN1,	"DARREN_BRAVO"},\
	{ BATSMAN2,	"CHRIS_GAYLE"},\
	{ BATSMAN3,	"EVIN_LEWIS"},\
	{ BATSMAN4,	"SHIMRON_HETMYER"},\
	{ BATSMAN5,	"ANDREW_RUSSELL"},\
	{ BATSMAN6,	"SHAI_HOPE"},\
	{ BATSMAN7,	"JASON_HOLDER"},\
	{ BATSMAN8,	"CARLOS_BARATHWAITE"},\
	{ BATSMAN9	"KEMAR_ROACH"},\
	{ BATSMAN10	"ASHLEY_NURSE"},\
	{ BATSMAN11	"OSHANE_THOMAS"}

#endif

#endif
